<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0SRMFK8" failures="1" tests="1" name="TestCase2 for interview" time="36.793" errors="0" timestamp="2022-01-07T00:47:46 ACDT">
  <testcase classname="PlaintTest.TestCase2" name="planitAssessment2" time="35.92">
    <failure type="java.lang.AssertionError" message="expected [Thanks Farhad1234@#$#@] but found [Thanks Farhad]">
      <![CDATA[java.lang.AssertionError: expected [Thanks Farhad1234@#$#@] but found [Thanks Farhad]
at PlaintTest.TestCase2.planitAssessment2(TestCase2.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- planitAssessment2 -->
</testsuite> <!-- TestCase2 for interview -->
